# fly.toml app configuration file for the historicalsights app
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "historicalsights"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8080 # Align with the updated server.js
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80 # Exposes HTTP on port 80 for users

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443 # Exposes HTTPS on port 443 for users

  [[services.http_checks]]
    interval = "10s" # How often the health check runs
    grace_period = "5s" # Time to wait before restarting the app
    method = "get"
    path = "/" # Root path to check if the app is running
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
